version: "3"
services:
    # MongoDB
    ms-scenario-evaluation-db:
        container_name: ms-scenario-evaluation-db
        image: mongo:4
        ports:
            - 27017:27017
        volumes:
            - ms-scenario-evaluation-volume:/data/db
    # Application components (API and web frontend)
    ms-scenario-evaluation:
        container_name: ms-scenario-evaluation
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
            - 3000:3000
            - 8000:80
        environment:
            - DB_HOST=ms-scenario-evaluation-db:27017
            - VUE_APP_BACKEND_URL=http://localhost:3000
        depends_on:
            - ms-scenario-evaluation-db
volumes:
    ms-scenario-evaluation-volume:
